**AbuseEval v1.0**

In [ ]:
# /content/abuseval_offenseval_train.tsv

In [ ]:
import pandas as pd

# Path to the TSV file
file_path = "/content/abuseval_offenseval_train.tsv"

# Load the TSV file into a Pandas DataFrame
dataset = pd.read_csv(file_path, sep='\t')

# Display the first few rows of the dataset
print(dataset.head())

# Display basic information about the dataset
print(dataset.info())

      id   abuse
0  86426  NOTABU
1  90194  NOTABU
2  16820  NOTABU
3  62688  NOTABU
4  43605  NOTABU
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13240 entries, 0 to 13239
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      13240 non-null  int64
 1   abuse   13240 non-null  object
dtypes: int64(1), object(1)
memory usage: 207.0+ KB
None

In [ ]:
dataset

          id   abuse
0      86426  NOTABU
1      90194  NOTABU
2      16820  NOTABU
3      62688  NOTABU
4      43605  NOTABU
...      ...     ...
13235  95338     EXP
13236  67210  NOTABU
13237  82921     IMP
13238  27429  NOTABU
13239  46552  NOTABU

[13240 rows x 2 columns]

In [ ]:
dataset.iloc[0]

id        86426
abuse    NOTABU
Name: 0, dtype: object

In [ ]:
dataset.iloc[1]

id        90194
abuse    NOTABU
Name: 1, dtype: object

In [ ]:
dataset.iloc[2]

id        16820
abuse    NOTABU
Name: 2, dtype: object

In [ ]:
dataset.keys()

Index(['id', 'abuse'], dtype='object')